//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployyeManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CaseRequests = new HashSet<CaseRequest>();
            this.CompanyEmployees = new HashSet<CompanyEmployee>();
            this.Invites = new HashSet<Invite>();
            this.LeaveCaseAllocations = new HashSet<LeaveCaseAllocation>();
            this.LeaveCaseAllocations1 = new HashSet<LeaveCaseAllocation>();
        }
    
        public int UserID { get; set; }
        public string EmailAdress { get; set; }
        public string Password_Salt { get; set; }
        public string Password_Hash { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] CreationDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseRequest> CaseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyEmployee> CompanyEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invite> Invites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCaseAllocation> LeaveCaseAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCaseAllocation> LeaveCaseAllocations1 { get; set; }
    }
}
